{
 "title": "PKS Namespace",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Count By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(pks_heapster_pod_uptime{cluster=~\"$cluster\", namespace_name=~\"$namespace\"}) by (cluster, namespace_name)",
     "legendFormat": "{{namespace_name}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Pod Container Count By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(pks_heapster_pod_container_uptime{cluster=~\"$cluster\",namespace_name=~\"$namespace\"}) by (cluster, namespace_name)",
     "legendFormat": "{{namespace_name}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_ns_memory_usage{cluster=~\"$cluster\", namespace_name=~\"$namespace\"}",
     "legendFormat": "{{namespace_name}} - {{cluster}}"
    }
   ]
  }
 ]
}