{
 "title": "PKS Node",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(pks_kube_node_info_gauge{cluster=~\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_cpu_node_utilization{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Usage Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_cpu_usage_rate{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_memory_working_set{cluster=~\"$cluster\",nodename=~\"$node\"} / pks_heapster_node_memory_node_capacity{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_memory_usage{cluster=~\"$cluster\",nodename=~\"$node\"} / pks_heapster_node_memory_node_capacity{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Allocatable vs Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "pks_kube_node_status_allocatable_cpu_cores_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "allocatable_core - {{cluster}}/{{node}}"
    },
    {
     "expr": "pks_kube_node_status_capacity_cpu_cores_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "capacity_core - {{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "Pod Resources Allocatable vs Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pks_kube_node_status_allocatable_pods_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "allocatable_pod_res - {{cluster}}/{{node}}"
    },
    {
     "expr": "pks_kube_node_status_capacity_pods_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "capacity_pod_res - {{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "Memory Allocatable vs Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_kube_node_status_allocatable_memory_bytes_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "allocatable_mem - {{cluster}}/{{node}}"
    },
    {
     "expr": "pks_kube_node_status_capacity_memory_bytes_gauge{cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "capacity_mem - {{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "Bytes Received Rate By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_node_network_rx{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Bytes Transferred Rate By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_node_network_tx{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Networking Errors By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_node_network_rx_errors{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])",
     "legendFormat": "rx_err - {{cluster}}/{{nodename}}"
    },
    {
     "expr": "rate(pks_heapster_node_network_tx_errors{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])",
     "legendFormat": "tx_err - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "File System Usage By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_filesystem_usage{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": " {{resource_id}} - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "File System - Available Storage by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_filesystem_limit{cluster=~\"$cluster\",nodename=~\"$node\"} - pks_heapster_node_filesystem_usage{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": " {{resource_id}} - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "File System - Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_filesystem_usage{cluster=~\"$cluster\",nodename=~\"$node\"} / pks_heapster_node_filesystem_limit{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": " {{resource_id}} - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IO Read Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 31 },
   "yaxes": [
    { "format": "Bps", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pks_heapster_node_disk_io_read_bytes{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])) by (cluster, nodename)",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IO Write Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pks_heapster_node_disk_io_write_bytes{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])) by (cluster, nodename)",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  }
 ]
}