{
 "title": "PKS Pod Container",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values(pks_kube_pod_container_info_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Rate By Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_container_cpu_usage_rate{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_container_memory_usage{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Disk IO Read Rate by Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_container_disk_io_read_bytes{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m])",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Disk IO Write Rate by Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_container_disk_io_write_bytes{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m])",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pod Containers Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_running_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (cluster, namespace, pod, container)",
     "legendFormat": "{{container}}/{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pod Containers Terminated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_terminated_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (cluster, namespace, pod, container)",
     "legendFormat": "{{container}}/{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pod Containers Terminated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_container_status_terminated_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}) by (cluster, namespace, pod, container)",
     "legendFormat": "{{container}}/{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Restarts per Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pks_kube_pod_container_status_restarts_total_counter{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{container}}/{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Page Faults Rate By Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "page faults / sec" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_container_memory_page_faults_rate{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "File System Usage By Pod Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_container_filesystem_usage{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}",
     "legendFormat": "{{resource_id}} - {{container_name}}/{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  }
 ]
}