{
 "title": "PKS Pod",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(pks_kube_node_info_gauge, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(pks_kube_pod_info_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_cpu_usage_rate{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_memory_usage{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Available in Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_ready_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", condition=\"true\"}) by (cluster, namespace)",
     "legendFormat": "{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Unavailable in Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_ready_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", condition=\"false\"}) by (cluster, namespace)",
     "legendFormat": "{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Running\"}) by (cluster, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Failed\"}) by (cluster, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Pending\"}) by (cluster, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pks_kube_pod_status_phase_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"}) by (cluster, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Page Faults Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "page faults / sec" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_pod_memory_page_faults_rate{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Bytes Received Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_network_rx{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Bytes Transferred Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_network_tx{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  },
  {
   "title": "Networking Errors By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(pks_heapster_pod_network_rx_errors{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "rx_err - {{pod_name}}/{{namespace_name}}/{{cluster}}"
    },
    {
     "expr": "rate(pks_heapster_pod_network_tx_errors{cluster=~\"$cluster\", namespace_name=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "tx_err - {{pod_name}}/{{namespace_name}}/{{cluster}}"
    }
   ]
  }
 ]
}